### ISSUE TITLE
Image build step error when pulling from package with zstd:chunked compression

### ISSUE THREAD

**Issue by wolfyreload** [ublue-os/image-template#23]
I'm not sure if this is the correct place to log this but Bazzite is switching over to zstd:chunked compression. I'd imagine that the other Ublue projects will be following suite for this. This appears to break the "Build Image" step in the image template. 

```
error creating build container: error preparing image configuration: error converting image "containers-storage:
[overlay@/home/runner/.local/share/containers/storage+/run/user/1001/containers]@a8494f3c7830b19cbf71ae6150ddd5b4d5e151d11ab10fd50d519edb2fa1d8fd" from 
"application/vnd.oci.image.manifest.v1+json" to "application/vnd.docker.distribution.manifest.v2+json": Error during manifest conversion: "application/vnd.oci.image.layer.v1.tar+zstd": 
zstd compression is not supported for docker images
```

To reproduce, edit the container file with:

* SOURCE_IMAGE="bazzite"
* SOURCE_SUFFIX="-nvidia"
* SOURCE_TAG="40-testing-20240627"

You can use any package that is using zstd:chunked compression to reproduce but this is the simplest example.

**Comment by wolfyreload** [comment]
Looks like it's something simple, we just need to change the running to explicitly be ubuntu-24.04 it looks like ubuntu-latest is only ubuntu-22.04

**Comment by castrojo** [comment]
When the Github runners for 24.04 go GA (sometime this month according to their roadmap) then all the default runners in github will be able to handle this. But we should probably recommend people pin to versions anyway.
