### ISSUE TITLE
Still using Ublue's Secure Boot key that built by this template?

### ISSUE THREAD

**Issue by xlionjuan** [ublue-os/image-template#31]
I've noticed that my Secure Boot is still valid after I rebased to my custom images, it this a security concern?

Though your repo needs to be public to freely publish images to `ghcr.io`, but it can still being used by bad actors before it takedown by GitHub, isn't it?

**Comment by EyeCantCU** [comment]
This is not a security concern. Everything in the stack is still signed with Ublue's key, regardless of whether you're using a custom image or not.
